const assets = {
  "Accessories": [
    "A Dollar Sui.png",
    "Angry Sign.png",
    "Axe.png",
    "Baseball Bat.png",
    "Bone.png",
    "Brush Teeth.png",
    "Bubble Gum.png",
    "Bulb.png",
    "Burger.png",
    "Candy Cane.png",
    "Carrot.png",
    "Chigar.png",
    "Cigarette.png",
    "Dead FIsh.png",
    "Donut.png",
    "Duckz Tounge.png",
    "Exclamation Mark.png",
    "Golden Snitch.png",
    "Ice cream stick.png",
    "Ice.png",
    "Katana.png",
    "Magic Wand.png",
    "Matchstick.png",
    "Mic.png",
    "nail bat.png",
    "Nail.png",
    "Party Horn.png",
    "Pencil.png",
    "Pigeon.png",
    "Pipe.png",
    "Pizza.png",
    "Question Mark.png",
    "Rainbow Puke.png",
    "Roses.png",
    "Shepherd's Crook.png",
    "Shootgun.png",
    "Smokerz.png",
    "Stick.png",
    "Straw.png",
    "Sui Mark.png",
    "Toothpick.png"
  ],
  "Head": [
    "Ahiru Headband.png",
    "Amethyst Bucket Hat.png",
    "Amethyst Trucker.png",
    "Anzac Bucket Hat.png",
    "Apache Headband.png",
    "Apple and Arrow.png",
    "Apple Mercury Backwards Trucker.png",
    "Apple.png",
    "Army Black Beret.png",
    "Army Blue Beret.png",
    "Army Orange Beret.png",
    "Army Red Beret.png",
    "Army.png",
    "Arrow Head.png",
    "Artistic Beret.png",
    "Banana Skin.png",
    "Black Bandana.png",
    "Black Beret.png",
    "Black Bucket.png",
    "Black Elvis Hair.png",
    "Black Headband.png",
    "Black Mohawk.png",
    "Black Pepper Fedora.png",
    "Blonde Elvis Hair.png",
    "Blue Bandana.png",
    "Blue Casual Bucket.png",
    "Blue Diamond Cap.png",
    "Blue Magic Hat.png",
    "Blue Mohawk.png",
    "Blue Rain Cap.png",
    "Blue Stocking Cap.png",
    "Branded Visor.png",
    "Brown Chicken.png",
    "Brown Mohawk.png",
    "Bunny.png",
    "Camelot Flat Cap.png",
    "Cape Cod Beanie.png",
    "Captain Hat.png",
    "Casual Bucket.png",
    "Celeste Fedora Hat.png",
    "Celeste Flat Cap.png",
    "Chateau Flat Cap.png",
    "Chicago Flat Cap.png",
    "Chicken Nest.png",
    "Christi Copper Trucker Hat.png",
    "Christine Beanie.png",
    "Clutchy 1st Cap.png",
    "Clutchy 2nd Cap.png",
    "Cowboy Hat.png",
    "Cranberry Beret.png",
    "CryptoPunk Mohawk.png",
    "Devil Horns.png",
    "Diamond Mohawk.png",
    "Downy Fedora Hat.png",
    "Earls Flat Cap.png",
    "Emerald Fedora Hat.png",
    "Fire Bush Trucker.png",
    "Fries Egg.png",
    "Frying Pan.png",
    "Fuchsia Beanie.png",
    "Fuscous Trucker.png",
    "Gold Tips Bucket Hat.png",
    "Golden Bandana.png",
    "Golden Crown.png",
    "Golden Dream Fedora Hat.png",
    "Golden Line Cowboy.png",
    "Golden Sui.png",
    "Green Bandana.png",
    "Green Bucket.png",
    "Green Cap.png",
    "Green Emerald Sui Visor.png",
    "Green Mohawk.png",
    "Green Stocking Cap.png",
    "Halo.png",
    "Havelock Blue Trucker.png",
    "Havelock Fedora Hat.png",
    "Havelock Mohawk.png",
    "Hibiscus Bucket Hat.png",
    "Hippie Pink Trucker.png",
    "Hopbush Trucker.png",
    "Hunter.png",
    "Ice Cream Cone.png",
    "Jester.png",
    "Kasa.png",
    "Keppler Backwards Trucker.png",
    "Lavender Fedora.png",
    "M visor.png",
    "Mahogany Beanie.png",
    "Mantis Bucket Hat.png",
    "Mariner Flat Cap.png",
    "Mariner Galliano Backwards Trucker.png",
    "Mariner Rose Backwards Trucker.png",
    "Masala Sunflowe Backwards Trucker.png",
    "Mayonaise.png",
    "Melting Cheese.png",
    "Mexican Hat.png",
    "Mexican Mercury Backwards Trucker.png",
    "Ocean Green Beanie.png",
    "Ocean Green Trucker.png",
    "Ochre Backwards Trucker.png",
    "Orange Beret.png",
    "Orange Headband.png",
    "Orchid Flat Cap.png",
    "Orchid Headband.png",
    "Party Hat.png",
    "Picton Headband.png",
    "Pink Bandana.png",
    "Pink Cap.png",
    "Pink Mohawk.png",
    "Pink Visor.png",
    "Police Hat.png",
    "Poop.png",
    "Pumice Beanie.png",
    "Purple Mohawk.png",
    "Rainbow Mohawk.png",
    "Ramen.png",
    "Raw Sienna Flat Cap.png",
    "Red Bandana.png",
    "Red Cap.png",
    "Red Headband.png",
    "Red Line Cowboy.png",
    "Red Magic Hat.png",
    "Red Mohawk.png",
    "Red Snapper Fedora.png",
    "Safety Helmet.png",
    "Saffron Beanie.png",
    "Sailor.png",
    "Samurai.png",
    "Santa Hat.png",
    "SDC Cap.png",
    "Shakespeare Beanie.png",
    "Shakespeare Fedora Hat.png",
    "Sport Headband.png",
    "Spray Bucket Hat.png",
    "Steel Blue Beanie.png",
    "Sui Cap.png",
    "Sui Trucker.png",
    "Sui Visor Hat.png",
    "SuiDuckz Trucker.png",
    "Sushi Chef.png",
    "The Internship.png",
    "Timberwolf Trucker.png",
    "Tomato Sauce.png",
    "Trapper Hat.png",
    "Tulip Tree Trucker.png",
    "Viking Flat Cap.png",
    "White Bandana.png",
    "White Bucket.png",
    "White Casual Bucket.png",
    "White Chicken.png",
    "White Headband.png",
    "White Mohawk.png",
    "Wizard Hat.png",
    "Yellow Cap.png",
    "Yellow Mohawk.png"
  ],
  "Eyes": [
    "3D Glasses.png",
    "Android.png",
    "Aviator.png",
    "Baseball.png",
    "Blue Sui Ski Glasses.png",
    "Bored.png",
    "Cyborg.png",
    "Disco.png",
    "DragonBall.png",
    "Golden Thug Glasses.png",
    "High.png",
    "Laser.png",
    "Monocle.png",
    "Mutant Glasses.png",
    "Nerd Glasses.png",
    "Oculus.png",
    "Orange Sui Ski Glasses.png",
    "Pirate.png",
    "Prof Glass.png",
    "Rainbow Glasses.png",
    "The Employe.png",
    "Thug Glasses.png",
    "Zombie.png"
  ],
  "Uniform": [
    "Amanita Mushrooms Tie.png",
    "Black and Yellow Scarf.png",
    "Black Bowtie.png",
    "Black Flanel.png",
    "Black Ninja.png",
    "Black Scarf.png",
    "Black Suit.png",
    "Black Sweater Sport.png",
    "Blue Bowtie.png",
    "Blue Employe.png",
    "Blue Flanel.png",
    "Blue Hoodie.png",
    "Blue Ninja.png",
    "Blue Scarf.png",
    "Blue Sweater Sport.png",
    "Blue White Scarf.png",
    "Bronze Chain Necklace.png",
    "Brown Bowtie.png",
    "Brown Scarf.png",
    "Brown Tie.png",
    "Cape.png",
    "Casual Sport Jacket.png",
    "Champion.png",
    "D Baseball Black.png",
    "D Baseball Blue.png",
    "D Baseball Red.png",
    "Dark Blue Hoodie.png",
    "Diamond Chain Necklace.png",
    "Flamingo Kimono Pajamas.png",
    "Golden Chain Necklace.png",
    "Green and White Scarf.png",
    "Green Bandana.png",
    "Green Bowtie.png",
    "Green Casual Jacket.png",
    "Green Hoodie.png",
    "Green Scarf.png",
    "Green Tie.png",
    "Internship.png",
    "Lab.png",
    "Leopard Kimono Pajamas.png",
    "LFG T-shirt Green.png",
    "LFG T-Shirt Red.png",
    "M Polo.png",
    "Ocean Polo.png",
    "Orange Prison.png",
    "Orange Sweater Sport.png",
    "Orange Tie.png",
    "Pink Bowtie.png",
    "Pink Hoodie.png",
    "Pink Polo.png",
    "Pink Scarf.png",
    "Pink Suit.png",
    "Polar Bear Pajamas.png",
    "Purple Bowtie.png",
    "Red and White Scarf.png",
    "Red Bandana.png",
    "Red Bowtie.png",
    "Red Employe.png",
    "Red Flanel.png",
    "Red Hoodie.png",
    "Red Ninja.png",
    "Red Scarf.png",
    "Samurai.png",
    "Silver Chain Necklace.png",
    "Spike Necklace.png",
    "Sui T-shirt.png",
    "The Gangster.png",
    "Vintage Sport Jacket.png",
    "White Bowtie.png",
    "White Hoodie.png",
    "White Scarf.png",
    "White Suit.png",
    "White Sweater Sport.png",
    "Yellow Bowtie.png",
    "Yellow Hoodie.png",
    "Yellow Polo.png",
    "Yellow Prison.png",
    "Yellow Scarf.png",
    "Yellow Tie.png"
  ],
  "Beak": [
    "Black.png",
    "Blue Gum.png",
    "Golden Beak.png",
    "Normal Beak.png",
    "Pink.png",
    "Red.png",
    "Rusty.png",
    "Silver Beak.png"
  ],
  "Skin": [
    "BlackScoter.png",
    "Duckling.png",
    "NorthernPintail.png",
    "PekingDuck.png",
    "RedHead.png",
    "RuddyDuck.png",
    "SpatulaClypeata.png"
  ],
  "Background": [
    "Algae.png",
    "Bermuda.png",
    "Blumine.png",
    "Catskill White.png",
    "Chess Board.png",
    "Chicago.png",
    "Christmas Candy.png",
    "Crail.png",
    "Cream Can.png",
    "CyberLine.png",
    "Eucalyptus.png",
    "Fire Area.png",
    "Fuchsia Blue.png",
    "Golden Dream.png",
    "Gray Suit.png",
    "Jungle Green.png",
    "Lavender Magenta.png",
    "Lavender Rose.png",
    "Mandy.png",
    "Peach.png",
    "PNG.png",
    "Police Line.png",
    "Radical Red.png",
    "Rose Fog.png",
    "Rosewood.png",
    "Sail.png",
    "Shamrock.png",
    "Silver Chalice.png",
    "Tahiti Gold.png"
  ]
};

export default assets;
